/**
 * Plain-English explanations for every technical term shown to
 * non-technical investors/developers. Single source of truth — the
 * <InfoTooltip term="..."> component looks keys up from here, so a term's
 * wording only ever needs to change in one place.
 */
export const GLOSSARY = {
  roas: {
    label: "ROAS (Return on Ad Spend)",
    text: "For every $1 spent on ads, how many dollars of revenue came back. A 1.5x ROAS means $1 of ad spend produced $1.50 of revenue from the customers it brought in. Below 1.0x means the ads spent more than they brought back — so far.",
  },
  cac: {
    label: "CAC (Customer Acquisition Cost)",
    text: "The average amount spent on ads to acquire one paying customer: total ad spend ÷ number of installs. A lower CAC means it's cheaper to bring in each new user.",
  },
  riskGrade: {
    label: "Risk grade",
    text: "A score from 0–100 (and a letter grade) summarizing this opportunity's track record — things like ROAS, refund rate, subscriber retention, and how long the app has been running. It's calculated from real historical numbers, not a guess or AI opinion.",
  },
  investorShare: {
    label: "Investor revenue share",
    text: "The percentage of profit (revenue above what you originally invested) that goes to investors, once your principal has been fully paid back. See \"Recoup-then-split\" below for how payouts actually work.",
  },
  returnCap: {
    label: "Return cap",
    text: "The maximum total multiple of your investment you can ever receive back. A 1.5x cap on a $100 investment means you can receive at most $150 total ($100 principal + $50 profit) — after that, all further revenue goes to the developer.",
  },
  recoupThenSplit: {
    label: "Recoup-then-split",
    text: "How every payout is calculated: first, 100% of attributed revenue goes toward paying back your original investment in full. Only once that's fully recouped does the investor/developer percentage split apply to anything earned above it — up to your return cap.",
  },
  minimumInvestment: {
    label: "Minimum investment",
    text: "The smallest amount you're allowed to invest under these terms.",
  },
  attributedRevenue: {
    label: "Attributed revenue",
    text: "Revenue from app purchases that can be reliably traced back to a specific marketing campaign, via install-tracking data (not just \"this app made money\" in general).",
  },
  adSpend: {
    label: "Ad spend",
    text: "Money the developer has actually spent running ads for this app, imported daily from the connected ad platform (e.g. Meta, TikTok).",
  },
  installs: {
    label: "Installs",
    text: "The number of times someone downloaded and opened the app after clicking one of its ads, as tracked by the attribution provider (e.g. AppsFlyer).",
  },
  payingCustomers: {
    label: "Paying customers",
    text: "How many of those installed users went on to actually pay for something in the app (a subscription, a one-time purchase, etc.).",
  },
  historicalWindow: {
    label: "Historical performance",
    text: "Real, already-happened numbers for this app — not a forecast. Everything on this page labeled with a data source (e.g. \"Meta\", \"AppsFlyer\") is pulled from that provider's real records, not invented.",
  },
  simulated: {
    label: "SIMULATED",
    text: "This is a demo/prototype environment — this specific number was generated by a deterministic demo-data script rather than pulled from a real advertising or revenue account. The math applied to it is identical to what a real deployment would use.",
  },
  fundingTerms: {
    label: "Standing funding terms",
    text: "Instead of a one-time fundraising goal, the developer sets an ongoing revenue-share agreement (a %, a return cap, a minimum) that stays open indefinitely. Any investor can fund under the current terms at any time — there's no \"raise\" to complete.",
  },
  capitalDeployed: {
    label: "Capital deployed",
    text: "How much of your invested money has actually been put to work funding real ad spend so far, versus sitting uncommitted.",
  },
  returnTimeline: {
    label: "Return timeline",
    text: "An estimate of how much of your investment you'd have back at different points in time, based on how quickly this specific app's revenue has actually arrived historically — not a generic assumption. Time horizons beyond the app's observed history are extrapolated from its recent trend and marked as such.",
  },
  avgDaysToRecoup: {
    label: "Avg. days to recoup principal",
    text: "Measured directly from this app's real past investments: on average, how many days after investing did it take for an investor to get their original principal fully paid back.",
  },
  avgDaysToCap: {
    label: "Avg. days to hit return cap",
    text: "Measured directly from this app's real past investments: on average, how many days after investing did it take for an investor to reach their maximum payout (the return cap).",
  },
  ledger: {
    label: "Ledger",
    text: "An append-only record of every dollar movement in the system — every ad spend, every payout, every reversal is its own permanent entry, never edited or deleted, so the full money trail can always be audited.",
  },
  bearBaseBull: {
    label: "Bear / Base / Bull",
    text: "Three what-if scenarios for how this investment could play out: Bear = a pessimistic case (historical ROAS × 0.6), Base = the straight historical average, Bull = an optimistic case (historical ROAS × 1.36). None are guaranteed — they're a range, not a prediction.",
  },
} as const;

export type GlossaryTerm = keyof typeof GLOSSARY;
